"""baseline schema

Revision ID: 4a6adfe08937
Revises: 
Create Date: 2026-02-21 13:31:47.960005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a6adfe08937'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_id'), 'datasets', ['id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.String(length=64), nullable=True),
    sa.Column('message', sa.String(length=512), nullable=True),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('steps_json', sa.Text(), nullable=True),
    sa.Column('result_ref', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_current_step'), 'jobs', ['current_step'], unique=False)
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_type'), 'jobs', ['type'], unique=False)
    op.create_table('ml_monitoring',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('drift_score', sa.Float(), nullable=False),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('mape', sa.Float(), nullable=True),
    sa.Column('segmented_json', sa.Text(), nullable=True),
    sa.Column('needs_retrain', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_monitoring_created_at'), 'ml_monitoring', ['created_at'], unique=False)
    op.create_index(op.f('ix_ml_monitoring_id'), 'ml_monitoring', ['id'], unique=False)
    op.create_table('model_rollouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('active_version', sa.String(length=64), nullable=True),
    sa.Column('canary_version', sa.String(length=64), nullable=True),
    sa.Column('canary_percent', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_rollouts_id'), 'model_rollouts', ['id'], unique=False)
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('artifact_path', sa.Text(), nullable=False),
    sa.Column('feature_schema_json', sa.Text(), nullable=True),
    sa.Column('training_data_ref', sa.Text(), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=True),
    sa.Column('artifact_gcs_uri', sa.Text(), nullable=True),
    sa.Column('vertex_model_resource', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_id'), 'models', ['id'], unique=False)
    op.create_index(op.f('ix_models_status'), 'models', ['status'], unique=False)
    op.create_index(op.f('ix_models_version'), 'models', ['version'], unique=True)
    op.create_table('od_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin_lat', sa.Float(), nullable=False),
    sa.Column('origin_lon', sa.Float(), nullable=False),
    sa.Column('dest_lat', sa.Float(), nullable=False),
    sa.Column('dest_lon', sa.Float(), nullable=False),
    sa.Column('depart_bucket', sa.String(length=32), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('base_distance_m', sa.Float(), nullable=False),
    sa.Column('base_duration_s', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_od_cache_day_of_week'), 'od_cache', ['day_of_week'], unique=False)
    op.create_index(op.f('ix_od_cache_depart_bucket'), 'od_cache', ['depart_bucket'], unique=False)
    op.create_index(op.f('ix_od_cache_dest_lat'), 'od_cache', ['dest_lat'], unique=False)
    op.create_index(op.f('ix_od_cache_dest_lon'), 'od_cache', ['dest_lon'], unique=False)
    op.create_index(op.f('ix_od_cache_id'), 'od_cache', ['id'], unique=False)
    op.create_index(op.f('ix_od_cache_origin_lat'), 'od_cache', ['origin_lat'], unique=False)
    op.create_index(op.f('ix_od_cache_origin_lon'), 'od_cache', ['origin_lon'], unique=False)
    op.create_table('prediction_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('origin_lat', sa.Float(), nullable=False),
    sa.Column('origin_lon', sa.Float(), nullable=False),
    sa.Column('dest_lat', sa.Float(), nullable=False),
    sa.Column('dest_lon', sa.Float(), nullable=False),
    sa.Column('features_json', sa.Text(), nullable=True),
    sa.Column('predicted_duration_s', sa.Float(), nullable=False),
    sa.Column('base_duration_s', sa.Float(), nullable=False),
    sa.Column('request_context_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_logs_id'), 'prediction_logs', ['id'], unique=False)
    op.create_index(op.f('ix_prediction_logs_model_version'), 'prediction_logs', ['model_version'], unique=False)
    op.create_table('error_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_logs_dataset_id'), 'error_logs', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_error_logs_id'), 'error_logs', ['id'], unique=False)
    op.create_index(op.f('ix_error_logs_stage'), 'error_logs', ['stage'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('depot_lat', sa.Float(), nullable=False),
    sa.Column('depot_lon', sa.Float(), nullable=False),
    sa.Column('num_vehicles', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('objective_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_makespan_s', sa.Float(), nullable=True),
    sa.Column('vehicle_capacity', sa.Integer(), nullable=True),
    sa.Column('workday_start', sa.String(length=5), nullable=True),
    sa.Column('workday_end', sa.String(length=5), nullable=True),
    sa.Column('infeasibility_reason', sa.Text(), nullable=True),
    sa.Column('eta_source', sa.String(length=32), nullable=True),
    sa.Column('traffic_timestamp_iso', sa.String(length=64), nullable=True),
    sa.Column('live_traffic_requested', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_dataset_id'), 'plans', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_table('predictions_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('od_cache_id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('predicted_duration_s', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['od_cache_id'], ['od_cache.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_cache_id'), 'predictions_cache', ['id'], unique=False)
    op.create_index(op.f('ix_predictions_cache_model_version'), 'predictions_cache', ['model_version'], unique=False)
    op.create_index(op.f('ix_predictions_cache_od_cache_id'), 'predictions_cache', ['od_cache_id'], unique=False)
    op.create_table('stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('stop_ref', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('postal_code', sa.String(length=32), nullable=True),
    sa.Column('demand', sa.Integer(), nullable=False),
    sa.Column('service_time_min', sa.Integer(), nullable=False),
    sa.Column('tw_start', sa.String(length=5), nullable=True),
    sa.Column('tw_end', sa.String(length=5), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('geocode_status', sa.String(length=32), nullable=False),
    sa.Column('geocode_meta', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stops_dataset_id'), 'stops', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_stops_geocode_status'), 'stops', ['geocode_status'], unique=False)
    op.create_index(op.f('ix_stops_id'), 'stops', ['id'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_idx', sa.Integer(), nullable=False),
    sa.Column('total_distance_m', sa.Float(), nullable=False),
    sa.Column('total_duration_s', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    op.create_index(op.f('ix_routes_plan_id'), 'routes', ['plan_id'], unique=False)
    op.create_table('actual_travel_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('origin_lat', sa.Float(), nullable=False),
    sa.Column('origin_lon', sa.Float(), nullable=False),
    sa.Column('dest_lat', sa.Float(), nullable=False),
    sa.Column('dest_lon', sa.Float(), nullable=False),
    sa.Column('timestamp_iso', sa.String(length=64), nullable=False),
    sa.Column('actual_duration_s', sa.Float(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('stop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actual_travel_times_id'), 'actual_travel_times', ['id'], unique=False)
    op.create_index(op.f('ix_actual_travel_times_route_id'), 'actual_travel_times', ['route_id'], unique=False)
    op.create_index(op.f('ix_actual_travel_times_stop_id'), 'actual_travel_times', ['stop_id'], unique=False)
    op.create_index(op.f('ix_actual_travel_times_timestamp_iso'), 'actual_travel_times', ['timestamp_iso'], unique=False)
    op.create_table('route_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('sequence_idx', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=True),
    sa.Column('eta_iso', sa.String(length=64), nullable=True),
    sa.Column('arrival_window_start_iso', sa.String(length=64), nullable=True),
    sa.Column('arrival_window_end_iso', sa.String(length=64), nullable=True),
    sa.Column('service_start_iso', sa.String(length=64), nullable=True),
    sa.Column('service_end_iso', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_stops_id'), 'route_stops', ['id'], unique=False)
    op.create_index(op.f('ix_route_stops_route_id'), 'route_stops', ['route_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_route_stops_route_id'), table_name='route_stops')
    op.drop_index(op.f('ix_route_stops_id'), table_name='route_stops')
    op.drop_table('route_stops')
    op.drop_index(op.f('ix_actual_travel_times_timestamp_iso'), table_name='actual_travel_times')
    op.drop_index(op.f('ix_actual_travel_times_stop_id'), table_name='actual_travel_times')
    op.drop_index(op.f('ix_actual_travel_times_route_id'), table_name='actual_travel_times')
    op.drop_index(op.f('ix_actual_travel_times_id'), table_name='actual_travel_times')
    op.drop_table('actual_travel_times')
    op.drop_index(op.f('ix_routes_plan_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_stops_id'), table_name='stops')
    op.drop_index(op.f('ix_stops_geocode_status'), table_name='stops')
    op.drop_index(op.f('ix_stops_dataset_id'), table_name='stops')
    op.drop_table('stops')
    op.drop_index(op.f('ix_predictions_cache_od_cache_id'), table_name='predictions_cache')
    op.drop_index(op.f('ix_predictions_cache_model_version'), table_name='predictions_cache')
    op.drop_index(op.f('ix_predictions_cache_id'), table_name='predictions_cache')
    op.drop_table('predictions_cache')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_dataset_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_error_logs_stage'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_id'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_dataset_id'), table_name='error_logs')
    op.drop_table('error_logs')
    op.drop_index(op.f('ix_prediction_logs_model_version'), table_name='prediction_logs')
    op.drop_index(op.f('ix_prediction_logs_id'), table_name='prediction_logs')
    op.drop_table('prediction_logs')
    op.drop_index(op.f('ix_od_cache_origin_lon'), table_name='od_cache')
    op.drop_index(op.f('ix_od_cache_origin_lat'), table_name='od_cache')
    op.drop_index(op.f('ix_od_cache_id'), table_name='od_cache')
    op.drop_index(op.f('ix_od_cache_dest_lon'), table_name='od_cache')
    op.drop_index(op.f('ix_od_cache_dest_lat'), table_name='od_cache')
    op.drop_index(op.f('ix_od_cache_depart_bucket'), table_name='od_cache')
    op.drop_index(op.f('ix_od_cache_day_of_week'), table_name='od_cache')
    op.drop_table('od_cache')
    op.drop_index(op.f('ix_models_version'), table_name='models')
    op.drop_index(op.f('ix_models_status'), table_name='models')
    op.drop_index(op.f('ix_models_id'), table_name='models')
    op.drop_table('models')
    op.drop_index(op.f('ix_model_rollouts_id'), table_name='model_rollouts')
    op.drop_table('model_rollouts')
    op.drop_index(op.f('ix_ml_monitoring_id'), table_name='ml_monitoring')
    op.drop_index(op.f('ix_ml_monitoring_created_at'), table_name='ml_monitoring')
    op.drop_table('ml_monitoring')
    op.drop_index(op.f('ix_jobs_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_current_step'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_datasets_id'), table_name='datasets')
    op.drop_table('datasets')
    # ### end Alembic commands ###
