steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - frontend/Dockerfile.cloudrun
      - -t
      - gcr.io/$PROJECT_ID/sg-route-opt-web:latest
      - --build-arg
      - VITE_API_BASE_URL=${_VITE_API_BASE_URL}
      - .
images:
  - gcr.io/$PROJECT_ID/sg-route-opt-web:latest
substitutions:
  _VITE_API_BASE_URL: https://sg-route-opt-api-7wgewdyenq-as.a.run.app
